<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260404093000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create tech_task table for admin kanban board';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE tech_task ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'title VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            .'status VARCHAR(24) NOT NULL, '
            .'position INT NOT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_tech_task_status_position ON tech_task (status, position)');
        $this->addSql('CREATE INDEX idx_tech_task_updated_at ON tech_task (updated_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tech_task');
    }
}
