<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260327142000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create spend table and seed March 2026 baseline data for income/spending plan/spend.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE spend ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'user_id INT NOT NULL, '
            .'spending_plan_id INT NOT NULL, '
            .'currency_id INT NOT NULL, '
            .'amount NUMERIC(12, 2) NOT NULL, '
            .'spend_date DATE NOT NULL, '
            .'comment TEXT DEFAULT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_spend_user ON spend (user_id)');
        $this->addSql('CREATE INDEX idx_spend_spending_plan ON spend (spending_plan_id)');
        $this->addSql('CREATE INDEX idx_spend_currency ON spend (currency_id)');
        $this->addSql('CREATE INDEX idx_spend_spend_date ON spend (spend_date)');
        $this->addSql('CREATE INDEX idx_spend_created_at ON spend (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE spend');
    }
}
