<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260407100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users_metadata table for storing user preferences';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE users_metadata ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'user_id INT NOT NULL, '
            .'preferences JSON NOT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_users_metadata_user_id ON users_metadata (user_id)');
        $this->addSql('ALTER TABLE users_metadata ADD CONSTRAINT fk_users_metadata_user FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users_metadata DROP CONSTRAINT fk_users_metadata_user');
        $this->addSql('DROP TABLE users_metadata');
    }
}
