<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260326113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create telegram_user table with optional relation to local users';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE telegram_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, telegram_id BIGINT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, status VARCHAR(24) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, authorized_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_telegram_user_user_id ON telegram_user (user_id)');
        $this->addSql('CREATE INDEX idx_telegram_user_status ON telegram_user (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_telegram_user_telegram_id ON telegram_user (telegram_id)');
        $this->addSql('ALTER TABLE telegram_user ADD CONSTRAINT fk_telegram_user_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE telegram_user DROP CONSTRAINT fk_telegram_user_user');
        $this->addSql('DROP TABLE telegram_user');
    }
}
