<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260326103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user table and seed default admin/test users';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_username ON "user" (username)');

        $adminPasswordHash = password_hash('admin', PASSWORD_BCRYPT);
        $testPasswordHash = password_hash('temp', PASSWORD_BCRYPT);

        $this->addSql(
            'INSERT INTO "user" (username, roles, password, created_at) VALUES (:username, :roles, :password, NOW())',
            [
                'username' => 'admin',
                'roles' => json_encode(['ROLE_ADMIN'], JSON_THROW_ON_ERROR),
                'password' => $adminPasswordHash,
            ]
        );

        $this->addSql(
            'INSERT INTO "user" (username, roles, password, created_at) VALUES (:username, :roles, :password, NOW())',
            [
                'username' => 'test',
                'roles' => json_encode(['ROLE_USER'], JSON_THROW_ON_ERROR),
                'password' => $testPasswordHash,
            ]
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user"');
    }
}
