<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331120500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create api_limit table for external API usage tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE api_limit ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'provider VARCHAR(32) NOT NULL, '
            .'character_count BIGINT NOT NULL, '
            .'character_limit BIGINT NOT NULL, '
            .'remaining_characters BIGINT NOT NULL, '
            .'usage_percent NUMERIC(6, 2) NOT NULL, '
            .'close_to_limit BOOLEAN NOT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_api_limit_provider ON api_limit (provider)');
        $this->addSql('CREATE INDEX idx_api_limit_created_at ON api_limit (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE api_limit');
    }
}
