<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260326170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create currency, spending_plan, and income tables with relations';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE currency ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'code VARCHAR(10) NOT NULL, '
            .'is_crypto BOOLEAN NOT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_currency_code ON currency (code)');
        $this->addSql(
            "INSERT INTO currency (code, is_crypto, created_at) VALUES "
            ."('GEL', FALSE, NOW()), "
            ."('EUR', FALSE, NOW()), "
            ."('USDT', TRUE, NOW())"
        );

        $this->addSql(
            'CREATE TABLE spending_plan ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'currency_id INT NOT NULL, '
            .'name VARCHAR(255) NOT NULL, '
            .'plan_type VARCHAR(24) NOT NULL, '
            .'date_from DATE NOT NULL, '
            .'date_to DATE NOT NULL, '
            .'limit_amount NUMERIC(12, 2) NOT NULL, '
            .'weight INT NOT NULL, '
            .'is_system BOOLEAN NOT NULL, '
            .'note TEXT DEFAULT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_spending_plan_currency ON spending_plan (currency_id)');
        $this->addSql('CREATE INDEX idx_spending_plan_date_from ON spending_plan (date_from)');
        $this->addSql('CREATE INDEX idx_spending_plan_date_to ON spending_plan (date_to)');
        $this->addSql('CREATE INDEX idx_spending_plan_plan_type ON spending_plan (plan_type)');
        $this->addSql(
            'ALTER TABLE spending_plan '
            .'ADD CONSTRAINT fk_spending_plan_currency '
            .'FOREIGN KEY (currency_id) REFERENCES currency (id) '
            .'ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE'
        );

        $this->addSql(
            'CREATE TABLE income ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'user_id INT NOT NULL, '
            .'currency_id INT NOT NULL, '
            .'amount NUMERIC(12, 2) NOT NULL, '
            .'amount_in_gel NUMERIC(12, 2) DEFAULT NULL, '
            .'rate NUMERIC(12, 4) DEFAULT NULL, '
            .'official_rated_amount_in_gel NUMERIC(12, 4) DEFAULT NULL, '
            .'comment TEXT DEFAULT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY(id)'
            .')'
        );
        $this->addSql('CREATE INDEX idx_income_user ON income (user_id)');
        $this->addSql('CREATE INDEX idx_income_currency ON income (currency_id)');
        $this->addSql('CREATE INDEX idx_income_created_at ON income (created_at)');
        $this->addSql('CREATE INDEX idx_income_amount_in_gel ON income (amount_in_gel)');
        $this->addSql(
            'CREATE INDEX idx_income_official_rated_amount_in_gel '
            .'ON income (official_rated_amount_in_gel)'
        );
        $this->addSql(
            'ALTER TABLE income '
            .'ADD CONSTRAINT fk_income_user '
            .'FOREIGN KEY (user_id) REFERENCES "user" (id) '
            .'ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
        $this->addSql(
            'ALTER TABLE income '
            .'ADD CONSTRAINT fk_income_currency '
            .'FOREIGN KEY (currency_id) REFERENCES currency (id) '
            .'ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE income DROP CONSTRAINT fk_income_user');
        $this->addSql('ALTER TABLE income DROP CONSTRAINT fk_income_currency');
        $this->addSql('DROP TABLE income');
        $this->addSql('ALTER TABLE spending_plan DROP CONSTRAINT fk_spending_plan_currency');
        $this->addSql('DROP TABLE spending_plan');
        $this->addSql('DROP TABLE currency');
    }
}
